general.import = [
  "~/.config/alacritty/themes/gruvbox_dark.toml",
  #"~/.config/alacritty/themes/tokyonight_night.toml",
]

[env]
TERM = "xterm-256color"

[font]
size = 17

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"
mods = "None"

[window]
startup_mode = "Maximized"
